### PR TITLE
Add userscript version

### PR DESCRIPTION
**Pull request by cnbeining**
And please add the following to Readme: (I didn't do this because YOU, @DennisSnijder need to go to settings, and enable the Github Pages on your master branch.)

```
# If you prefer the userscript method...

0. Set Github Pages at your main branch in case you stress Github's server: Pages is served via the CDN as static file so this is better for Github.
1. Install a Userscript manager: refer to https://github.com/OpenUserJs/OpenUserJS.org/wiki/Userscript-beginners-HOWTO 
2. In browser, go to  https://{YOUR_REPO_URL}}/MakeGithubGreatAgain/MakeGithubGreatAgain.user.js
3. Install the script

Now you have it! It will kick in a sec later, but easier to deploy.
```

### CODE REVIEW

**Comment by DennisSnijder** [comment]
OK!
Ill enable the Github pages.

**Comment by DennisSnijder** [comment]
Also feel free to create a PR for the GitHub page 👍

**Comment by cnbeining** [comment]
Nah you do not need a pr for that: just set that to the master branch and
we are good. The point is we want to serve the js file from the CDN as
static file rather than making one checkout per request on the back end,
which shall stress the server and will have potential MIME issues.

2017年2月10日 下午4:41，"Dennis Snijder" <notifications@github.com>写道：

**Comment by DennisSnijder** [comment]
Alright, i made another branch for the github pages (I needed this for google site verification) so people can download the extension from the google extension store.

Thanks for the support by the way!

**Pull request merged**
