### PR TITLE
Restore commonly used reds, greens, blues and purples from old CSS (fix #49)

### LINKED ISSUE #49: Save the colors!!!
I think you need to save us from new github colors! Especially links!

### PR DESCRIPTION
**Pull request by svnpenn**

### CODE REVIEW

**Comment by svnpenn** [comment]
https://github.com/DennisSnijder/MakeGithubGreatAgain/issues/49

**Comment by DennisSnijder** [comment]
Awesome!
I'm missing the old private colored button.
image

**Comment by svnpenn** [comment]
@DennisSnijder I dont use private repos, so I do not intend to fix that

**Comment by svnpenn** [comment]
@DennisSnijder I just pushed another commit. I was not targeted to your issue, but it might fix it

**Comment by DennisSnijder** [comment]
Is this PR ready for review?

**Comment by svnpenn** [comment]
@DennisSnijder I made a couple of commits since this, but I have already deleted my fork. I would say to go ahead and merge this and then I can open a 2nd PR with the rest if you want

**Pull request closed without merging**
